import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //  --> default setting tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // guidesSidebar: [{type: 'autogenerated', dirName: './knowlegde-base'}]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: "category",
      label: "Projects",
      items: [{ type: "autogenerated", dirName: "projects" }],
    },
    {
      type: "category",
      label: "Pentesting",
      items: [{ type: "autogenerated", dirName: "pentesting" }],
    },
  ],
};

export default sidebars;
