name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  create-or-update-pr:
    name: Create or update PR
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/create-pr.yaml

  build-and-deploy-to-pages:
    name: Build website and deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
